config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  get 'user/new'
  get 'user/signup' , to: 'user#new', as: 'signup'
  post '/signup', to: 'user#create'
  get 'user/success'

  get 'login', to: 'sessions#new', as: 'login'
  post 'user/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  #delete '/tasks/:id', to: 'tasks#destroy', as: 'task'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "user#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sessions.rb
class Sessions < ApplicationRecord

    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true

    belongs_to :user
    #self.primary_key = 'task_id'

    #after_save :update_completed_tasks_count
    #after_destroy :update_completed_tasks_count
    after_save :update_daily_achievement


    #def update_completed_tasks_count
        # Logic to update the completed tasks count
        #completed_tasks_count = Task.where(completed: true).count
    #end
      
    def update_daily_achievement
        if completed_changed? && completed?
          today = Time.zone.today
          daily_tasks = user.tasks.where(created_at: today.beginning_of_day..today.end_of_day)
          completed_tasks = daily_tasks.where(completed: true)
          self.daily_count = completed_tasks.count
          self.percentage =((daily_count.to_f / daily_tasks.count) * 100).round(2)
          save
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  
    # Validations
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :first_name, presence: true
    validates :last_name, presence: true
  
    has_many :tasks
    has_many :sessions

    
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    #before_action :require_login
    protect_from_forgery with: :exception
    private
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def require_login
      unless logged_in?
        redirect_to login_path, alert: 'Please log in.'
      end
    end
end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      render :login
    end
  
    def create
      # Retrieve the user based on the provided username/email
      user = User.find_by(email: params[:email])
  
      if user && user.authenticate(params[:password])
        # Set the user ID in the session to indicate successful login
        session[:user_id] = user.id
        redirect_to tasks_path, notice: 'Logged in successfully!'
      else
        redirect_to login_path, notice: 'Invalid email or password'
      end
    end
  
    def destroy
      # Clear the session and log out the user
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged out successfully!'
    end
end
  
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_login

    def index
      @task = current_user.tasks
      @percentage = (current_user.tasks.where(completed: true). count/current_user.tasks.count.to_f)*100
      @f_percentage = sprintf("%.1f", @percentage)
      if @f_percentage == '100.0'
        flash[:notice] = 'Welldone! All tasks completed!'
      elsif @f_percentage >= '70.0' && @f_percentage <= '99.0'
        flash[:notice] = "You're almost there!"
      elsif @f_percentage >= '50.0' && @f_percentage <= '69.0'
        flash[:notice] = "Keep going, you can do it!"
      else
        flash[:notice] = "Wonderful start!"
      end 
    end
      
    def new
      @task = current_user.tasks.new
      render :create
    end
  
    def create
      @task = current_user.tasks.new(task_params)
    
      if @task.save
        redirect_to task_path(@task), notice: 'Task created successfully!'
      else
        render :index
      end
    end
  
    def show
        @task = current_user.tasks.find(params[:id])
    end
  
  
    def edit
        @task = current_user.tasks.find_by(id: params[:id])
    end
  
  
    def update
      @task = current_user.tasks.find(params[:id])
      if @task.update(task_params)
        flash[:notice] = 'Task updated successfully!'
        redirect_to tasks_path(@task)
      else
        render :edit
      end
    end
  
    def completed?
      completed
    end
  
  
    def destroy
      @task = current_user.tasks.find_by(id: params[:id])
      @task.destroy
      flash[:notice] = 'Task deleted successfully!'
      redirect_to tasks_path(@task)
    end
  
    #Yet to be implemented
    #def update_daily_achievement
    # if completed_changed? && completed?
    #    today = Time.zone.today
    #    daily_tasks = Task.where(user_id: user_id, created_at: today.beginning_of_day..today.end_of_day)
    #    completed_tasks = daily_tasks.where(completed: true)
    #    self.daily_count = completed_tasks.count
    #    self.percentage = (daily_count.to_f / daily_tasks.count * 100).round(2)
    #    save
    # end
    #end
    
  
private
  
    def task_params
      params.require(:task).permit(:title, :body, :completed)
    end
  
    
end
  
  

app/controllers/user_controller.rb
# app/controllers/users_controller.rb
class UserController < ApplicationController
  
    def new
      @user = User.new
      render :signup
    end
  
    def create
      @user = User.new(user_params)
  
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = 'Sign up successful! Welcome.'
        redirect_to root_path 
      else
        render :new
      end
    end
  
    def completed_tasks_count
      tasks.where(completed: true).count
    end
  
  private
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :completed_tasks_count)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JTASK</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <%= javascript_include_tag 'rails-ujs' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'blogo.jpg' %>
  <style>
  .flash{
     color: dodgerblue;
      font-size: 1.5em;
      font-family: Georgia, 'Times New Roman', Times, serif;
      text-align: center;
    }
  </style>
  </head>

<body>
  <div class="container">
    <% if flash[:notice] %>
      <p class="flash">
        <%= flash[:notice] %>
      </p>
    <% end %>
    <br>
      <%= yield %>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

app/views/tasks/create.html.erb
<style>
  .container{
      padding: 5%;
    }
  h1{
      color: dodgerblue;
      font-size: 3.5em;
      font-family: Georgia, 'Times New Roman', Times, serif;
    }
  </style>
<body>
  <div class="container">
  <h1>New Task</h1>

<%= form_with model: @task, url: tasks_path, method: :post do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Enter your task title', required: true%>
  </div>
  
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :body, class: 'form-control', placeholder: 'Describe your task',required: true %>
  </div>

  <br>
  <%= f.submit "Add Task", class: 'btn btn-warning' %>
  </div>
<% end %>
</div>
<script src="bootstrap.min.js"></script>
</body>
</html>

app/views/tasks/edit.html.erb
<style>
  .container{
      padding: 5%;
    }
  h1{
      color: dodgerblue;
      font-size: 3.5em;
      font-family: Georgia, 'Times New Roman', Times, serif;
    }
  </style>
  <body>
  <div class="container">
  <h1>Edit Task</h1>

<%= form_with model: @task do |f| %>
<div class="form-group">
  <%= f.check_box :completed%>
  <%= f.label :Completed, "Task Completed" %>
</div>

<div class="form-group">
  <%= f.label :Title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Enter your task title', required: true%>
  </div>
  
  <div class="form-group">
  <%= f.label :Description %>
  <%= f.text_area :body, class: 'form-control', placeholder: 'Describe your task',required: true %>
  </div>

  <br>
  <%= f.submit "Edit Task", class: 'btn btn-warning' %>

  </div>
<% end %>

</body>
</html>

app/views/tasks/index.html.erb
<style>
  h1{
    color: dodgerblue;
    font-size: 3.5em;
    font-family: Georgia, 'Times New Roman', Times, serif;
  }
  .but{
    display: flex;
    flex-wrap: wrap;
    margin: 5%;
  }
</style>
  <body>
  <h1>Task List</h1>
  <h4>Completed Tasks: <%= current_user.tasks.where(completed: true).count %></h4>
  <p>Percentage: <%=@f_percentage%>%</p> 
  <%# end %>
  <p><%#= (current_user.tasks.all).count%></p>

  <p id="time"><p><br>

<table class="table table-hover table table-striped table">
  <thead>
    <tr>
      <th class="table-light"> </th>
      <th class="table-primary">Title</th>
      <th class="table-light">Description</th> 
      <th class="table-primary">Completed?</th>
      <th class="table-light">Actions</th>
    </tr>
  </thead>
  <tbody>
    
      <tr>
        <% current_user.tasks.each do |task|%>
        <%= form_with model: task do |f| %>
        <td class="table-light">
        <%= f.check_box :completed, checked: task.completed?, class: 'form-check-input disabled' %>
        <% end %> 
        </td>
        <td class="table-primary"><%= task.title %></td>
        <td class="table-light"><%= task.body %></td>
        <td class="table-primary"><%= task.completed? ? "True" : " "%></td>
        
        <td class="table-light">
          <div class="but">
            <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-outline-warning'%>
            <%= link_to 'View',task_path(task), class: 'btn btn-outline-primary'%>
          </div>  
        </td>
      </tr>
        <% end %>
  </tbody>
</table>

<div>
<div class="but">
<%= link_to "Add Task", new_task_path, class: "btn btn-warning" %><br>
<%= link_to "Logout", logout_path, method: :delete, class: "btn btn-warning", data: { confirm: 'Are you sure you want to log out?'} %>
</div>
</div>

<script>
//document.addEventListener('DOMContentLoaded', function() {
 updateTime()
 //updatePercentage()
  // Function to update the current time
  function updateTime() {
    var currentTimeElement = document.getElementById('time');
    var currentTime = new Date();
    currentTimeElement.innerHTML = 'Time: ' + currentTime.toLocaleTimeString();
  }
  setInterval(updateTime, 1000);

  /*var checkboxes = document.querySelectorAll('input[name="task"]');

  // Function to update the percentage will be updated later!!
  function updatePercentage() {
    var completedCount = 0;
    var totalCount = checkboxes.length;

    // Count the number of completed tasks
    checkboxes.forEach(function(checkbox) {
      if (checkbox.checked) {
        completedCount++;
      }
    });

    // Calculate the percentage
    var percentage = (completedCount / totalCount) * 100;

    // Update the percentage element
    var percentageElement = document.getElementById('percentage');
    percentageElement.textContent = "Today's Percentage:"+ percentage.toFixed(2) + '%';
  }

  // Add event listeners to the checkboxes
  checkboxes.forEach(function(checkbox) {
    checkbox.addEventListener('change', updatePercentage);
  });
  });*/

  
  


</script>
</body>
</html>

app/views/tasks/show.html.erb
<style>
  h1{
    color: dodgerblue;
    font-size: 3.5em;
    font-family: Georgia, 'Times New Roman', Times, serif;
  }
  .but{
    display: flex;
    flex-wrap: wrap;
    margin: 5%;
  }
</style>
<body>
<h1>Task Details</h1>

<p><strong>Completed:<%= @task.completed? ? "True" : "False"%></p>
<p><strong>Title:</strong> <%= @task.title %></p>
<p><strong>Description:</strong> <%= @task.body %></p>

<div class="but">
<%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-warning" %><br>
<%= link_to "View All", tasks_path, class: "btn btn-primary" %><br>
<%= form_for @task, url: task_path(@task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} do |f| %>
<%= f.submit 'Delete', class: 'btn btn-danger'%>
<% end %>
</div>
</body>
</html>

app/views/user/home.html.erb
<style>
    .hero-image {
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      height: 200px;
      display: flex;
      justify-content: center;
      align-items: center;
      color: yellow;
    }
    h1{
      font-size: 4.5em;
      font-weight: 2000px;
      font-family: Georgia, 'Times New Roman', Times, serif;
      background-color:dodgerblue;
      padding: 3%;
      border-radius: 15%;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="hero-image">
      <h1>JTASK</h1>
    </div>
    <div class="row">
      <div class="col-md-5">
        <h2>Stay Organized</h2>
        <p>Keep track of your tasks and stay organized with our powerful Todo App.</p>
        <%= image_tag 'todotask.jpg', class: "img-fluid" %>
      </div>
      <div class="col-md-7">
        <h2>Get Things Done</h2>
        <p>Manage your tasks efficiently and boost your productivity.</p>
        <%= image_tag 'Jtaskpic.png', class: "img-fluid" %>
      </div>
    </div><br>
    <div class="btn-group" role="group" aria-label="Navigation">
      <%= link_to "Login", login_path, class: "btn btn-primary" %>
      <%= link_to "Sign up", signup_path, class: "btn btn-warning" %>
    </div>
  </div>
</body>
</html>

app/views/user/signup.html.erb
<style>
  .container{
    padding: 5%;
  }
  h2{
    color: dodgerblue;
    font-size: 3.5em;
    font-family: Georgia, 'Times New Roman', Times, serif;
  }
  p{
    font-family: Georgia, 'Times New Roman', Times, serif;  
  }
</style>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">

<h2>Sign Up</h2>

<%= form_for @user, url: '/signup', html: { class: 'needs-validation' }, novalidate: true do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'Enter your first name', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Enter your last name', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: 'Enter your email address', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', placeholder: 'Enter your password', required: true %>
  </div>

  <div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
</div>

  <%= f.submit 'Sign Up', class: 'btn btn-warning' %>
<% end %>

      </div>
    </div>
  </div>
  <script src="bootstrap.min.js"></script>
</body>
</html>